### ISSUE TITLE
Wrong date selection

### ISSUE THREAD

**Issue by ysnskrtan** [CooperRS/RMDateSelectionViewController#43]
If i set datePickerMode to UIDatePickerModeDate it gives me wrong outputs for April, May, June, July, August, September and October.

Here are the samples

March        1 2001  -> Successfully selected date: 2001-03-01 00:00:00 +0000  True
April           1 2001  -> Successfully selected date: 2001-03-31 23:00:00 +0000  False
May            1 2001  -> Successfully selected date: 2001-04-30 23:00:00 +0000  False
June           1 2001 -> Successfully selected date: 2001-05-31 23:00:00 +0000   False
July             1 2001 -> Successfully selected date: 2001-06-30 23:00:00 +0000  False
August        1 2001 -> Successfully selected date: 2001-07-31 23:00:00 +0000  False
September 1 2001  -> Successfully selected date: 2001-08-31 23:00:00 +0000  False
October      1 2001 -> Successfully selected date: 2001-09-30 23:00:00 +0000  False
November  1 2001 -> Successfully selected date: 2001-11-01 00:00:00 +0000   True

How can we solve? I tried some adding timezone or changing time interval property but it does not work.

**Comment by CooperRS** [comment]
If you log an NSDate object it is always logged in UTC time zone. So depending on your timezone, these dates should be ok...
