### ISSUE TITLE
"Clear" date/time field option

### ISSUE THREAD

**Issue by sedwo** [CooperRS/RMDateSelectionViewController#44]
Really nice control.  I've embedded it into my custom UITableViewCell and have had several requests now for people asking how they can "clear" the date/time value in the cell.

Unlike a regular UITextField that provides that tiny 'x' icon to clear its field, my thought for your control was to put in a simple "Clear" button that would return an empty string, and thus erasing any value within the cell.

Thoughts?

![clearfeature](https://cloud.githubusercontent.com/assets/1434449/6073867/82e75cd2-ad82-11e4-985d-678e05cc388b.png)

**Comment by CooperRS** [comment]
Hi,

Why do you want to clear the content of a date cell? Usually, the date is needed to continue the process in which the date is selected. Clearing the date would not be really useful I think :/...

The only reason to clear a text field is that the user does not need to delete all characters before he can type a new text. An empty string in the text field usually also means, that the process where the text of the text field is used, cannot be continued (like when adding a folder. A folder without a name is not useful).

**Comment by sedwo** [comment]
Hi,

In my forms app though with many and various input text fields, users can fill out the details in any order they wish as well as skip (leave empty) fields that might not yet be relevant at that time.  It's like filling out an application form, and if the user "accidentally" inputs a date/time field that she didn't mean to or was mistaken about, it would be beneficial to them to have a way to clear it.

Most intuitively, people will search the path that lead them to input that value with a way to also clear it.  Hence they tap on the cell, get the pop-up to only realize there is no way back.

I honestly did try to make the change myself, but only broke things so terribly that I'm embarrassed to admit my lack of AutoLayout skills.  :/

A less then ideal fix to this issue that I've experimented with was enable these selective date/time cells to have a "swipe to clear" feature.  Essentially using the "swipe to delete" feature to clear the text.  But it's not intuitive and I'm not happy with that approach.  It should really be up to the control that maintains CRUD over the text field.

**Comment by CooperRS** [comment]
Hi,

First: Sorry for the long delay!

Your are right, a swipe to clear feature is not optimal. What do you think of adding a clear button (just like the textview does) to the cell? The behavior of the button is known by the user and therefore should be more intuitively. Also this saves some taps as the user does not need to open the RMDateSelectionViewController again.

**Comment by sedwo** [comment]
I've thought about it, but the UX for text input fields is that once they are engaged, the little 'x' button appears.

In our case here, the moment the field is engaged, the RMDateSelectionViewController is displayed.  So we don't have any access to the cell.

Showing a permanent 'x' button on the cell constantly would make it look weird compared to the other cells that only show it upon engagement.

**Comment by CooperRS** [comment]
In the current master branch adding arbitrary buttons is possible. Thus, a clear button can be implemented, too.
