### ISSUE TITLE
Hide status bar

### ISSUE THREAD

**Issue by mhergon** [CooperRS/RMDateSelectionViewController#45]
Hi,

Is there any way to hide status bar? My app doesn't show status bar, but when I will show date selector, this appears and breaks design.

Thanks!

**Comment by CooperRS** [comment]
In the git HEAD I have added a property `statusBarHiddenMode`. This property can have three values:

* ***RMStatusBarHiddenModeDefault***: On iOS 7, the status bar is not hidden in any orientation. On iOS 8, the status is not hidden in portrait mode and hidden in landscape mode.
* ***RMStatusBarHiddenModeAlways***: The status bar is always hidden, regardless of orientation and iOS version.
* ***RMStatusBarHiddenModeNever***: The status bar is never hidden, regardless of orientation and iOS version.

Please give it a try. If it helps in your case, you can close the ticket.

**Comment by mhergon** [comment]
This change is available in CocoaPods?

Thanks!

**Comment by CooperRS** [comment]
Nope. For usual, I first add the changes to the git repo, so the user of my control (you) can test these changes. This way I'm not pushing something broken to CocoaPods. I will add the changes to CocaPods after you tested though ;)

**Comment by mhergon** [comment]
Hi again,

Works like a charm!

**Before**
![captura de pantalla 2015-02-10 a las 16 59 55](https://cloud.githubusercontent.com/assets/621373/6130597/44f54624-b146-11e4-985b-1973b6eb8347.png)

**After**
![captura de pantalla 2015-02-10 a las 16 59 42](https://cloud.githubusercontent.com/assets/621373/6130602/49dddc5a-b146-11e4-8624-34949da94749.png)

Thanks!

**Comment by CooperRS** [comment]
Published to CocoaPods in version 1.4.3. Did some renaming though to ensure that RMDateSelectionViewController and RMPickerViewController can be used at the same time.
