### ISSUE TITLE
Reduce transparency

### ISSUE THREAD

**Issue by scottphc** [CooperRS/RMDateSelectionViewController#48]
Settings > General > Accessibility > Increase Contrast > Reduce Transparency > Enable

![ios simulator screen shot mar 9 2015 4 24 38 pm](https://cloud.githubusercontent.com/assets/1115510/6551803/16c15476-c679-11e4-9bf9-13283145421d.png)

I try to fix but no idea. Any solutions? The same problem happens in RMPickerViewController.
Thanks!

**Comment by CooperRS** [comment]
Actually, thats pretty easy. You have to disable the transparency of RMDateSelectionViewController/RMPickerViewController when UIAccessibilityReduceTransparencyEnabled() returns YES.

But I think this should be done by the control automatically. So just wait a minute, I'll implement ;)...

**Comment by CooperRS** [comment]
Implemented in commit 9e64871464381f6a4d4ebfca81b275db5d42434a which is available in the current git HEAD. I would like you to test the new options and if it works for you, you can close the ticket :)

**Comment by scottphc** [comment]
Work perfectly! Thanks:)
