### ISSUE TITLE
Make compatible with App Extensions

### ISSUE THREAD

**Issue by CooperRS** [CooperRS/RMDateSelectionViewController#51]
RMDateSelectionViewController relies on UIWindow for presentation. But an App Extension cannot present new UIWindows. Thus, RMDateSelectionViewController is incompatible with App Extensions. This should be fixed...

**Comment by romaincointepas** [comment]
Thanks for this (and your answer on the 2 other issues). I'm very new to iOS dev so I can't help much, but I'm looking forward to this.

**Comment by CooperRS** [comment]
I created a new branch called AppExtensions. In this branch is a new version of RMDateSelectionViewController which does not rely on UIWindows anymore. Instead I'm using the standard iOS methods for presenting UIViewControllers (i.e. `presentViewController:animated:completionHandler:`)

I would appreciate, if you could give it a try and give me some feedback :)

**Comment by romaincointepas** [comment]
Seems to work like a charm! Thanks for this

**Comment by CooperRS** [comment]
Great, I think this branch will become version 1.5.x then :)
