### ISSUE TITLE
'RMDateSelectionViewController' does not have a member named 'setLocalizedTitleForSelectButton'

### ISSUE THREAD

**Issue by romaincointepas** [CooperRS/RMDateSelectionViewController#52]
Maybe I'm not getting something, but I can't use the setLocalized* methods.

![screen shot 2015-03-26 at 9 13 32 am](https://cloud.githubusercontent.com/assets/797899/6850811/a4344850-d398-11e4-916c-30b01a97e711.png)

**Comment by CooperRS** [comment]
It's a static method. So you need to write RMDateSelectionViewController.setLocalizedTitleForSelectButton() ;)

**Comment by romaincointepas** [comment]
Oh okay. Shouldn't this be an instance method like `hideNowButton()` and others? (I could have multiple RMDateSelectionViewController with different purposes)

**Comment by CooperRS** [comment]
Actually, this property should be settable via a Proxy API, very much like the UIAppearance API. But this is something for a future version ;)
