### ISSUE TITLE
More / Different Buttons

### ISSUE THREAD

**Issue by Jules2010** [CooperRS/RMDateSelectionViewController#53]
I would like to a button which has "Don't select an End Date", I have this as a full width button in an action sheet at the moment, but I need to upgrade, is there anyway I can add a full width button.

I thought I could re-use the now button and move it underneath the picker, but I can't :(

Any thoughts ?

**Comment by CooperRS** [comment]
Unfortunately, this is now way of adding new buttons using the current API. But I think this may be a nice to have feature for the future.

Also relates to #44

**Comment by Jules2010** [comment]
That would be awesome

**Comment by CooperRS** [comment]
Hi,

what sort of customizations would you need for the buttons? Is it enough to be able to give a text or an image for the button or would you also want to change the font, the text color, the backgroundcolor and so on?

I'm thinking about an UIAlertController like API...

**Comment by Jules2010** [comment]
As long as the style matched, just text, but full width, like an alert view

**Comment by CooperRS** [comment]
As you may have noticed I opened a new branch called feature/MoreButtons. I juts uploaded a first version which allows to add an arbitrary number of buttons. I would appreciate if you would take a look at it and give me some feedback.

Screenshot below shows current development state...

![ios simulator screen shot 19 04 2015 19 59 46](https://cloud.githubusercontent.com/assets/342095/7220620/127ace8a-e6cf-11e4-9669-90773c7e0f07.png)

**Comment by Jules2010** [comment]
That looks good, although personally I was looking for full width buttons.

**Comment by CooperRS** [comment]
You mean Select and Cancel at the bottom? You can do that ;)

**Comment by CooperRS** [comment]
Like that?

![ios simulator screen shot 19 04 2015 20 29 04](https://cloud.githubusercontent.com/assets/342095/7220730/c2817178-e6d2-11e4-8b95-48e2a4440048.png)

**Comment by Jules2010** [comment]
Yep :)

Best regards,

Jules.
Sent from my iPhone

You can follow me on twitter @MindwarpJules

On 19 Apr 2015, at 19:29, Roland Moers <notifications@github.com> wrote:

Like that?

**Comment by Jules2010** [comment]
I actually meant additional buttons

Best regards,

Jules.

On 19 Apr 2015, at 19:29, Roland Moers <notifications@github.com> wrote:

Like that?

**Comment by CooperRS** [comment]
Solved in the current master branch
