### ISSUE TITLE
Looking help

### ISSUE THREAD

**Issue by Imtayaz** [CooperRS/RMDateSelectionViewController#54]
Thanks for your control. This is really helpful.
Now I am trying to implement this with Swift. I am not sure how do I use following property.

@property (nonatomic, copy) void (^selectButtonAction)(RMDateSelectionViewController *controller, NSDate *date);

Thanks in advance.

**Comment by CooperRS** [comment]
Hi, you can use it like follows:

```swift
func buttonTouched(sender:AnyObject) {
    let controller = RMDateSelectionViewController.dateSelectionController();

    controller.selectButtonAction = {(controller:RMDateSelectionViewController?, date:NSDate?) in
        //Do something here...
        NSLog("Selected date: %@", date!);
    }
        
    self.presentViewController(controller, animated: true, completion: nil);
}
```

Hope it helps :)
