### ISSUE TITLE
How to use RMDateSelectionViewController in swift . Please provide a sample code

### ISSUE THREAD

**Issue by neoD1** [CooperRS/RMDateSelectionViewController#55]

**Comment by SunburstEnzo** [comment]
Why is this closed? I seem to be having problems with using this in Swift as well, most things work exept for .show() and .delegate = self

![screen shot 2015-05-01 at 12 45 03 pm](https://cloud.githubusercontent.com/assets/1451896/7429787/f6505fa6-efff-11e4-8879-c6b2b3b06850.png)

**Comment by CooperRS** [comment]
You seem to be using version 1.5 of RMDateSelectionViewController. In this version the interface changed. Please take another look a the interface. The delegate has been replaced by blocks and the date selection view controller is presented by using apples standard method `presentViewController:animated:completion:`

**Comment by SunburstEnzo** [comment]
Ah ok my bad, thanks for the reply! And thanks for a great component, it's really useful :)
