### ISSUE TITLE
Buttons hidden when contained in tab bar

### ISSUE THREAD

**Issue by k4roshi** [CooperRS/RMDateSelectionViewController#56]
If the DatePicker is presented inside a tab bar controller the buttons are hidden underneath the tab bar. 
![schermata 2015-05-05 alle 15 31 44](https://cloud.githubusercontent.com/assets/443208/7473506/fd2b60c0-f33b-11e4-86c6-fa19b76cf789.png)

**Comment by CooperRS** [comment]
You should be able to present the date selection view controller by using the tab bar controller. So something like 
`[self.tabBarController presentViewController:dateSelectionVC animated:YES completion:nil]` should work

**Comment by k4roshi** [comment]
Works nicely!
Thanks a lot
