### ISSUE TITLE
Landscape issue

### ISSUE THREAD

**Issue by SMFakhir** [CooperRS/RMDateSelectionViewController#57]
For iOS 7 support, I'm using 1.4.3 as advised in docs.
Its working well when i switch to landscape from portrait but unable to adjust frame when i open it in landscape.

**Comment by CooperRS** [comment]
Do you experience the bug on an iPhone or an iPad?

**Comment by Syed-Muhammad-Fakhir** [comment]
its in iPhone.

**Comment by CooperRS** [comment]
Can you attach an screenshot of the bug? This would help me a lot to identify the problem :)

**Comment by Syed-Muhammad-Fakhir** [comment]
Sure, Here it is

![snap](https://cloud.githubusercontent.com/assets/7599643/7675462/27d9c6c0-fd52-11e4-9580-3c2af8287e97.png)

**Comment by Syed-Muhammad-Fakhir** [comment]
Also, there is one more issue when opening in landscape and switching to portrait, the picker's user-interaction gets disabled somehow.

**Comment by CooperRS** [comment]
I'm dropping support for iOS 7 and RMDateSelectionViewController versions below 2.0.0.

There are multiple bugs when rotating from or to landscape and unfortunately, I don't have the time to maintain and develop multiple versions of my controls :/. So I decided to drop support for versions below 2.0.0.

I'll still continue to develop
