### ISSUE TITLE
Visual bug on iPad (as popover)

### ISSUE THREAD

**Issue by romaincointepas** [CooperRS/RMDateSelectionViewController#58]
Extra space misaligning the buttons.

![img_0089](https://cloud.githubusercontent.com/assets/797899/7665058/9eb23e6a-fb5b-11e4-9d1f-d39736a055c2.PNG)

**Comment by CooperRS** [comment]
Which version of RMDateSelectionViewController are you using?

**Comment by romaincointepas** [comment]
Latest release (1.5.1).

I'm attaching the popover to a barItem (if that changes anything).

**Comment by CooperRS** [comment]
Hmm, I planning version 2.0.0 of RMDateSelectionViewController which is based on RMActionController. I think this version will fix your bug. If you could test this with the current master branch you would do me a favor :)

**Comment by romaincointepas** [comment]
I will try the master branch right now.

BTW, I'm getting a nasty `Errno::ENOENT - No such file or directory` when doing a `pod install` with:
`pod 'RMDateSelectionViewController', :git => 'https://github.com/CooperRS/RMDateSelectionViewController.git'`

Before filing an issue with Cocoapods, I wanted to check if you could reproduce.

**Comment by CooperRS** [comment]
Fixed the podspec file. Thank you!
