### ISSUE TITLE
Install instructions fail

### ISSUE THREAD

**Issue by djclarkson** [CooperRS/RMDateSelectionViewController#59]
platform :ios, '8.0'
pod "RMDateSelectionViewController", "~> 2.0.0"

Result:

[!] Unable to satisfy the following requirements:
- `RMDateSelectionViewController (~> 2.0.0)` required by `Podfile`

**Comment by CooperRS** [comment]
This because version 2.0.0 has not been release yet. I would recomment to use 1.5.1 for the moment :)

**Comment by robertibiris** [comment]
On the Cocoapods site there apperars to be the new version 2.0.0 already realeased, but I still get the same error than @djclarkson 

platform :ios, '8.0'
pod "RMDateSelectionViewController", "~> 2.0.0"

Result:

[!] Unable to satisfy the following requirements:

RMDateSelectionViewController (~> 2.0.0) required by Podfile

**Comment by CooperRS** [comment]
Hmm, did you try to run 'pod update' instead of 'pod install'? It looks like CocoaPods did not update the currently available pods

**Comment by sebasx** [comment]
I have the same problem

**Comment by CooperRS** [comment]
Did you try to run `pod update` instead of `pod install`?

**Comment by sebasx** [comment]
Yes, the same problem

http://s12.postimg.org/4zfxazmct/preview.png

**Comment by CooperRS** [comment]
Hmm, version 2.0.0 has been release in the meantime and it is definitely available in the specs repo. To me this seems like an CocoaPods bug. Did you try to delete `~/.cocoapods/repos` and run `pod update` afterwards?

This make CocoaPods re-download the specs repo with all specs in it. Version 2.0.0 should be available then...

**Comment by sebasx** [comment]
still the same :/

**Comment by CooperRS** [comment]
Hmm, next I would try to add the CocoaPods Specs Repo as explicit source. You can do this by adding `source 'https://github.com/CocoaPods/Specs.git'` at the beginning of your Podfile. Besides, which version of CocoaPods are you using?

**Comment by CooperRS** [comment]
Closing because of missing activity. If this issue persists, please reopen the ticket :)
