### ISSUE TITLE
Cannot find protocol declaration following Pod update

### ISSUE THREAD

**Issue by djclarkson** [CooperRS/RMDateSelectionViewController#60]
Following a Pod update I get the error "Cannot find protocol declaration for RMDateSelectionViewControllerDelegate" on the following interface:

@interface HHCreateTaskViewController () <UITextViewDelegate, RMDateSelectionViewControllerDelegate>

When I cmd-click RMDateSelectionViewControllerDelegate I get "Symbol not found". The library is imported in the controller with the following line:

#import "RMDateSelectionViewController.h"

And the Podfile:
platform :ios, '8.0'
pod 'RMDateSelectionViewController'

I tried cleaning the project folder, restarting Xcode etc.

**Comment by CooperRS** [comment]
The protocol RMDateSelectionViewControllerDelegate is not used anymore. It has been replaced by blocks called selectAction and the optimal cancelAction and nowAction

**Comment by djclarkson** [comment]
Thank you!
