### ISSUE TITLE
import fail on Swift project

### ISSUE THREAD

**Issue by retsohuang** [CooperRS/RMDateSelectionViewController#61]
![screen shot 2015-06-10 at 10 12 55 pm](https://cloud.githubusercontent.com/assets/785920/8084501/ef9d6018-0fbd-11e5-9ff7-4c4da135a937.png)

The error cause by this line
![screen shot 2015-06-10 at 10 17 06 pm](https://cloud.githubusercontent.com/assets/785920/8084599/77967b44-0fbe-11e5-9811-6403b1348cc3.png)

Change to `#import <RMActionController/RMActionController.h>` solve the issue

P.S.Same issue at RMPickerViewController

**Comment by CooperRS** [comment]
Are you a bridging header?

**Comment by retsohuang** [comment]
I use as framework.

**Comment by ivangodfather** [comment]
import RMActionController

**Comment by retsohuang** [comment]
@CooperRS @ivangodfather I modified issue description, hope it will clear the problem.

**Comment by ivangodfather** [comment]
@retsohuang seems it doesnt work with swift,i opened another issue.

**Comment by CooperRS** [comment]
I'll look into it :)

**Comment by CooperRS** [comment]
I just created a demo swift project which uses both RMDateSelectionViewController and RMPickerViewController. After running `pod install` you still have to add a bridging header as you are using Objective-C Code in a Swift project (refer to https://medium.com/@stigi/swift-cocoapods-da09d8ba6dd2).

So all that's missing is a bridging header. As explained on that side just add a new header file, add Objective-C import statements for RMDateSelectionViewController and/or RMPickerViewController to that header and set the header as bridging header in the Build Settings of your project. The site above links to an Apple side with some more details about adding a bridging header.

I'll append my demo project for you as reference. Give me a second to find out how GitHub will let me do :)

**Comment by CooperRS** [comment]
Hmm, 3 options:

1. `#import "RMActionController.h"`
2. `#import <RMActionController.h>`
3. `#import <RMActionController/RMActionController.h>`

The first option is the only option when manually installing RMDateSelectionViewController. The second option only works when installing using CocoaPods without frameworks. And the third option works for all CocoaPods installations (framework based and library based).

As I do not recommend manually installing RMDateSelectionViewController/RMPickerViewController (no automatic dependency management), I think I'm going with option 3.

Are there any options I missed? In particular, an option, that works under all circumstances?

**Comment by retsohuang** [comment]
Other objc pods going with option 3 (e.g. JSQMessagesViewController)

**Comment by CooperRS** [comment]
I'll go with option 3, too. IT#s already changed in the current git head but I'll also release a version 2.0.1. Should be available soon.

**Comment by retsohuang** [comment]
Cool, thanks.
