### ISSUE TITLE
Swift: NSAssert

### ISSUE THREAD

**Issue by ivangodfather** [CooperRS/RMDateSelectionViewController#62]
Hi. im trying to use this library in swift, however i get this error:
NSAssert(self.contentView != nil, @"Error: The view of an RMActionController has been loaded before a contentView has been set. You have to set the contentView before presenting a RMActionController.");

Any ideas?

        let selectAction = RMAction(title: AppearanceService.textById(Texts.Ok), style: RMActionStyle.Done, andHandler: { (actionController) -> Void in
            
        })
        let cancelAction = RMAction(title: AppearanceService.textById(Texts.Cancel), style: RMActionStyle.Done, andHandler: { (actionController) -> Void in
            
        })
        let dateSelectionController = RMActionController(style: RMActionControllerStyle.White, selectAction: selectAction, andCancelAction: cancelAction)
        presentViewController(dateSelectionController, animated: true, completion: nil)

**Comment by CooperRS** [comment]
I'll look into it...

**Comment by CooperRS** [comment]
OK, the problem is in this line:

```swift
let dateSelectionController = RMActionController(style: RMActionControllerStyle.White, selectAction: selectAction, andCancelAction: cancelAction)
```

You are instantiating an RMActionController while you should instantiate an RMDateSelectionViewController or RMPickerViewController. Depends on what you need.

So the following line should work (and does in my tests):

```swift
let dateSelectionController = RMDateSelectionViewController(style: RMActionControllerStyle.White, selectAction: selectAction, andCancelAction: cancelAction)
```

Hope I could help! :)
If you have any further questions just ask.

**Comment by ivangodfather** [comment]
When i try to import in my bridign header i get "Could not build mode 'RMDateSelectionViewController'

http://s23.postimg.org/5079h5iq2/Screen_Shot_2015_06_11_at_08_34_38.jpg

http://s7.postimg.org/oh26exbyi/Screen_Shot_2015_06_11_at_08_36_51.jpg

**Comment by ivangodfather** [comment]
I solved this issue changing the import to #import <RMActionController/RMActionController.h>
inside the RMDateSelectionViewController.h but i still can't show the datepicker.

 Warning: Attempt to present <RMDateSelectionViewController: 0x7fd7397a0480>  on <xxx.ProfileVC: 0x7fd7394e8210> which is already presenting (null)

http://s15.postimg.org/z6cgnmuzv/Screen_Shot_2015_06_11_at_08_49_32.png

**Comment by ivangodfather** [comment]
I also tried your other library from Cocoapods RMPickerViewController, and its hasnt got the method 'actionControllerWithStyle..' veeery strange?

**Comment by CooperRS** [comment]
Which version of RMPickerController has been installed?

**Comment by ivangodfather** [comment]
Using RMDateSelectionViewController (2.0.0)
Using RMPickerViewController (1.4.1)

**Comment by ivangodfather** [comment]
iMac-Apps:Project alex$ cat Podfile
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'AsyncImageView', '~> 1.5.1'
pod 'Alamofire', :git => "git@github.com:Alamofire/Alamofire.git", :branch => 'xcode-6.3'
pod 'ObjectMapper', :git => "git@github.com:Hearst-DD/ObjectMapper.git", :branch => 'swift-1.2'
pod 'CSStickyHeaderFlowLayout'
pod 'Shimmer'
pod 'RMDateSelectionViewController'
pod 'RMPickerViewController'
pod 'RMActionController', '~> 1.0.0'

**Comment by CooperRS** [comment]
Hmm, version 1.4.1 of RMPickerViewController is not up to date. You may try to run `pod update`

**Comment by ivangodfather** [comment]
After updating:
I had to change inside RMPickerViewController.h the import statement to:

#import <RMPickerViewController/RMActionController.h>
instead of #import <RMActionController.h>
And then the pickerview doesnt show up, and the second time i get:
<RMPickerViewController: 0x7fda12f89240>  on <ApperStreet.AddressVC: 0x7fda15237cd0> which is already presenting (null)

extension AddressVC: AddressViewDelegate {
    func didConfirmAddress(view: AddressView) {
        let view = view as AddressView
        var currentAddress = Address()
        currentAddress.address = view.addressTextField.text
        currentAddress.addressName = view.nameAddressTextField.text
        currentAddress.phone = view.telfTextField.text
        
        CurrentCustomer.setAddress(currentAddress)
        populateExclusiveSelectorView()
        view.isEditing = false
        
    }
    
    func didClickInPostalCode(view: AddressView) {
        let selectAction = RMAction(title: "Select", style: RMActionStyle.Done) { (controller) -> Void in
            
        }
        let cancelAction = RMAction(title: "Cancel", style: RMActionStyle.Cancel) { (controller) -> Void in
            
        }
        let pickerController = RMPickerViewController(style: RMActionControllerStyle.White, selectAction: selectAction, andCancelAction: cancelAction)
        pickerController.picker.delegate = self
        pickerController.picker.dataSource = self
        presentViewController(pickerController, animated: true, completion: nil)

    }
}



extension AddressVC: UIPickerViewDataSource {
    func pickerView(pickerView: UIPickerView, numberOfRowsInComponent component: Int) -> Int {
        return 1
    }
    
    
    func pickerView(pickerView: UIPickerView, titleForRow row: Int, forComponent component: Int) -> String! {
        return "test"
    }
    
    func numberOfComponentsInPickerView(pickerView: UIPickerView) -> Int {
        return 1
    }
}

extension AddressVC: UIPickerViewDelegate {
    
}

**Comment by ivangodfather** [comment]
any updates?

**Comment by CooperRS** [comment]
Hi, sorry for the long delay :/

Can you provide me with a demo project where the issue occurs? I'm not able to reproduce the issue...

**Comment by ivangodfather** [comment]
2.0.1 seems working properly
