### ISSUE TITLE
Minimum Interval Does not work

### ISSUE THREAD

**Issue by wajidp** [CooperRS/RMDateSelectionViewController#63]
Date picker minimum interval for 30 minute doesn't work

**Comment by CooperRS** [comment]
Do you mean the `minuteInterval` property of UIDatePicker? Works great for me if I set it in the demo project in `-[RMViewController openDateSelectionController]:105`.

![ios simulator screen shot 05 07 2015 13 02 26](https://cloud.githubusercontent.com/assets/342095/8511441/5c0d35c8-2316-11e5-96f8-00900c9f2088.png)

**Comment by wajidp** [comment]
Thanks..
