### ISSUE TITLE
Sometimes disappears offscreen

### ISSUE THREAD

**Issue by themobilegurus** [CooperRS/RMDateSelectionViewController#64]
Occasionally disappears offscreen when presented (if you look closely, you see the component being animated upwards and disappear). This blocks the rest of the app and requires a restart.

It can be fixed by changing the `modalPresentationStyle` to `UIModalPresentationOverFullScreen` (iOS 8)

Steps we did to reproduce this;
- iOS 8 (seems to be fixed on iOS 9)
- Present a UIViewController as modal (via IB Segue)
- Present the RMDateSelectionViewController from the presented UIViewController
- Press select/cancel on the RMDateSelectionViewController to dismiss it
- Dismiss the presented UIViewController
- Present the same UIViewController as modal again (via IB Segue)
- Present the RMDateSelectionViewController from the presented UIViewController
-> Bug will occur, app will be 'blocked'.

**Comment by CooperRS** [comment]
Hmm, if iOS 9 fixes the issue it most likely it an iOS bug. I'll give your steps a try and give some feedback asap :)

**Comment by CooperRS** [comment]
Unfortunately, I cannot reproduce the bug :/
I modified the demo project such that I can modally present a view controller. I then ran that project in iOS Simulator 8.4 and 8.1 but I was not able to reproduce the bug.

I made a screencast of that test session but GitHub won't allow me to upload a .mov file. You can download it here: http://cooperrs.de/Test.mov

Did I do the right steps to reproduce the bug?

**Comment by themobilegurus** [comment]
Thanks for trying to reproduce it, those seem like the right steps.. 
I'll try to strip our code, reproduce the problem and send you the project.

**Comment by CooperRS** [comment]
Are there any news on the sample project?

**Comment by themobilegurus** [comment]
We've been really busy. So far we haven't been able to reproduce the bug in a clean project, so there might be different circumstances in which the bug occurs. Since the fix is simple, we're going to let it rest for now. Thanks for your trouble so far!
