### ISSUE TITLE
Date picker wheel not showing in iOS 8 iPhone

### ISSUE THREAD

**Issue by udayasri** [CooperRS/RMDateSelectionViewController#66]
Hi,

When I run the example application in the simulator with blur version , it shows the date picker wheel , but when I run the same example application in my iPhone ( iOS 8 ) it doesn't work .. It shows the black pop up with title & buttons , but not the date picker wheel. Without blur  version it works well .. Any idea how to fix this ..  

Thanks a lot

**Comment by CooperRS** [comment]
Hi,

this is a known issue on device and some simulators. I already filed an Apple bug but Apple did not want to fix it yet :/

Roland

**Comment by udayasri** [comment]
oh really ! sad to hear that as I want to use this library so badly . :(

**Comment by CooperRS** [comment]
You have some options though:

1) I think there are some hacks around to make the labels of the date picker show white text. Not the option to choose for the App Store, though :/
2) You could implement your own date picker using UIPickerView. The black mode of RMPickerViewController is not broken :)
3) You can use another date picker which supports a black mode and present it using RMActionController

Roland

**Comment by udayasri** [comment]
Thanks a lot @CooperRS .. I'll look in to it ..

**Comment by ricardopereira** [comment]
It gives a warning:
`<UIVisualEffectView 0x1672b920> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.`

I don't know if it's related.

**Comment by CooperRS** [comment]
No it's not. This message is also logged when showing a white version of RMDateSelectionViewController. But the white version shows just fine.

**Comment by jyounus** [comment]
Did Apple ever fix this bug? I'm still able to reproduce this issue on my device. :/
