### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by ahsolanki** [CooperRS/RMDateSelectionViewController#68]
I called below function on button action,

`func openStartTime()
    {
        view.endEditing(true)
        let style = RMActionControllerStyle.White
        
        let selectAction = RMAction(title: "Select", style: RMActionStyle.Done) { controller in
            
            if let pickerController = controller as? RMDateSelectionViewController
            {
                let formatter = NSDateFormatter.init()
                formatter.dateFormat = "HH:mm"
                let date1 = formatter.stringFromDate(pickerController.datePicker.date)
                self.txtTime.text = date1
            }
        }
        
        let cancelAction = RMAction(title: "Cancel", style: RMActionStyle.Cancel) { _ in
            
        }
        
        let actionController = RMDateSelectionViewController(style: style, title: "HelloWorld", message: "Select Start Time.", selectAction: selectAction, andCancelAction: cancelAction)!;
        
        actionController.datePicker.datePickerMode = .Time
        actionController.datePicker.minimumDate = NSDate()
        
        //Now just present the date selection controller using the standard iOS presentation method
        appDelegate.window?.rootViewController!.presentViewController(actionController, animated: true, completion: nil)
    }`

and got below error,
**_fatal error: unexpectedly found nil while unwrapping an Optional value_**

**Comment by CooperRS** [comment]
What line is causing the issue? Is it somewhere in 
> appDelegate.window?.rootViewController!.presentViewController(actionController, animated: true, completion: nil)

?

**Comment by CooperRS** [comment]
Closing because of missing response.
