### ISSUE TITLE
Getting wrong time

### ISSUE THREAD

**Issue by KarthikMandava** [CooperRS/RMDateSelectionViewController#69]
I am getting wrong time but date was correct. Even I have set timezone to local still getting wrong time. Please help me out from this.

**Comment by CooperRS** [comment]
Hi there,

did you just NSLog the time to verify that the right time has been selected? Because I think NSLog always logs UIDates in UTC timezone.

Best regards,
Roland

**Comment by CooperRS** [comment]
Closing due to missing response :/

If this issue still exists please reopen the issue.
