### ISSUE TITLE
Dismiss parent view controller after picking the time

### ISSUE THREAD

**Issue by dafdafydd** [CooperRS/RMDateSelectionViewController#70]
Hello,

I wonder if it is possible to dismiss the picker and the parent view controller at the same time. I experimented with putting dismissViewControllerAnimated in the Done action but it does not dismiss the parent - only RMDateSelectionViewController disappears.

Is there any way it could be done?

**Comment by CooperRS** [comment]
Hi there,

I think you can do this by calling ```dismissViewControllerAnimated``` twice. However, this might be bad style :D.

Best regards,
Roland

**Comment by dafdafydd** [comment]
Thank you! This is how I overcome it for now but I wonder if there a "cleaner" way to do it.
