### ISSUE TITLE
Readme is old & init doesn't work

### ISSUE THREAD

**Issue by jonathanng** [CooperRS/RMDateSelectionViewController#71]
The code below no longer works, but the readme file still reflects this convenience method. Also style is not defined.

``` Objective-C
RMDateSelectionViewController *dateSelectionController = [RMDateSelectionViewController actionControllerWithStyle:style selectAction:selectAction andCancelAction:cancelAction];
```

Looking through the code, I tried using the init method:

``` Objective-C
RMDateSelectionViewController *dateVC = [[RMDateSelectionViewController alloc] initWithStyle:RMActionControllerStyleWhite
                                                                                       title:nil
                                                                                     message:nil
                                                                                selectAction:selectAction
                                                                             andCancelAction:cancelAction];
```

But I get the error:

```
-[RMDateSelectionViewController initWithStyle:title:message:selectAction:andCancelAction:]: unrecognized selector sent to instance 0x7fe84664bf30
```

**Comment by CooperRS** [comment]
Ohoh, sry for reporting! :)
I'll fix the ```README.md``` as soon as possible.

**Comment by CooperRS** [comment]
I removed the code examples from the `README.md` file. Instead I created a new wiki page about [How to use RMDateSelectionViewController](https://github.com/CooperRS/RMDateSelectionViewController/wiki/Usage). The code examples on this page are available in Swift and Objective C and should work again 😄

If you still encounter problems with the new wiki page please reopen this issue or create a new one.
