### ISSUE TITLE
White button text

### ISSUE THREAD

**Issue by klauslanza** [CooperRS/RMDateSelectionViewController#72]
Hi,
I'm using the component as from the README, but getting white button, quite unreadable.

Same result with various combinations of 
    pickerController.disableBlurEffectsForBackgroundView = NO;
    pickerController.disableBlurEffectsForContentView = NO;

Any idea?
iOS 9.3.x 

Cheers

![schermata 2016-08-03 alle 16 24 33](https://cloud.githubusercontent.com/assets/1684798/17369086/11be208c-5997-11e6-8c3e-67967aa46125.png)

**Comment by klauslanza** [comment]
Ok, my fault. It is working correctly using just 
    pickerController.disableBlurEffects = YES;

Thanks for this great project, using it a lot lately!

**Comment by jordanmaguire** [comment]
Awesome 👍  Thanks for this. Had the same issue
