### ISSUE TITLE
set max date

### ISSUE THREAD

**Issue by embassem** [CooperRS/RMDateSelectionViewController#77]
how to set the max date  for the picker ?

**Comment by CooperRS** [comment]
Hi there!

First take a look at [Wiki (Usage)](https://github.com/CooperRS/RMDateSelectionViewController/wiki/Usage#date-picker) on how to access the `datePicker` property of any `RMDateSelectionViewController`. After having obtained the `UIDatePicker` itself, you probably want to call [`maximumDate`](https://developer.apple.com/reference/uikit/uidatepicker/1615999-maximumdate?language=objc) and/or [`minimumDate`](https://developer.apple.com/reference/uikit/uidatepicker/1615980-minimumdate?language=objc) on it.

If this answers your question, feel free to close the ticket 🙂.

Best regards,
Roland
