### ISSUE TITLE
Chartage Support?

### ISSUE THREAD

**Issue by KelvinEC** [CooperRS/RMDateSelectionViewController#78]
This Library has Carthage support? If no, has any plan to add it?

**Comment by CooperRS** [comment]
Yes, Carthage is being supported. Is it not working for you?

**Comment by KelvinEC** [comment]
I didnt test but has nothing on Readme about it. I think if can add it, will be very good.

**Comment by CooperRS** [comment]
Ok, then it seems to be fine.

Take a closer look at the readme. In particular at the badges to the right of the title 🙂.
