### ISSUE TITLE
Change font color

### ISSUE THREAD

**Issue by weilong88** [CooperRS/RMDateSelectionViewController#86]
Is this still possible? I've tried changing your uidatepicker variable but to no avail.

**Comment by CooperRS** [comment]
Hi there!

Unfortunately, the `UIDatePicker` used internally does not allow to change the appearance of it.

If you want to use a more customizable date picker control, you can use the [`RMActionController`](https://github.com/CooperRS/RMActionController/) to present it in a similar manner 🙂.

Best regards,
Roland
